### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by W-quan** [nassendelft/alfred-android-emulator#1]
OS: 10.13.6 (17G65)

alfred:3.6.2

**Comment by W-quan** [comment]
The error log:

```
[2019-03-07 10:34:17][input.scriptfilter] Queuing argument ''
[2019-03-07 10:34:17][input.scriptfilter] Script with argument '' finished
[2019-03-07 10:34:17][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "/Users/wzq/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/20405A4C-EE9D-4CDE-9574-926D6DB93A54", line 9, in <module>
    emulators = check_output([path, "-list-avds"]).decode("utf-8").rstrip().split('\n')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by nassendelft** [comment]
the error log is telling you why it isn't workign:

Permission denied

either you set the wrong path in the variable (which is my guess) or the
emulator binary just have the wrong permission.

**Comment by W-quan** [comment]
I set the  "emu_path" with avd path.😅
