### ISSUE TITLE
Error when launching emulator

### ISSUE THREAD

**Issue by avxkim** [nassendelft/alfred-android-emulator#3]
```
Code 1: Traceback (most recent call last):
  File "/Users/alexanderkim/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/DB6EAB41-B193-439D-9A72-1A0311A7976B", line 9, in <module>
    emulators = check_output([path, "-list-avds"]).decode("utf-8").rstrip().split('\n')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

I've set emu_path to `$HOME/Library/Android/sdk/emulator`
android_path `$HOME/Library/Android/sdk`

Here's 2 cases:

1. If i use as "emu_path": `$HOME/Library/Android/sdk/emulator`
When i type "emu" in alfred it throws an error about permission.
2. If i use as "emu_path": `$HOME/Library/Android/sdk/tools/emulator`
Then "emu" in alfred works, but it won't actually launch an emulator, instead it throws an error:

```
PANIC: Missing emulator engine program for 'x86' CPU.
```

From CLI if i use `$HOME/Library/Android/sdk/tooks/emulator @Pixel_XL_API_28` it throws that PANIC error, but if i use `$HOME/Library/Android/sdk/emulator/emulator @Pixel_XL_API_28` it does work.

**Comment by avxkim** [comment]
**Figured out**

Used wrong path, had to use as "emu_path": `$HOME/Library/Android/sdk/emulator/emulator`

By the way, when emulator is launched, i can't call it again if i type "emu" and choose emulator i previously launched, just like any other app. Is it possible to implement this feature?
